books/urls.py
from django.urls import path
from . import views


app_name = 'books'

urlpatterns = [
    path('', views.books, name='books'),  
]

landingpage/urls.py
from django.urls import path
from . import views


app_name = 'landingpage'

urlpatterns = [
    path('', views.home, name='home'),  
    path('add_status/', views.add_status, name='add_status'),
]

login/urls.py
from django.urls import path
from . import views


app_name = 'login'

urlpatterns = [  
    path('login/', views.login, name='login'), 
    path('', views.homei, name='homei'),
]

profileKu/urls.py
from django.urls import path
from . import views


app_name = 'profileKu'

urlpatterns = [
    path('', views.profile, name='profile'),  
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('profile/', include('profileKu.urls')),
    path('books/', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    

    
]

books/models.py
from django.db import models

# Create your models here.

landingpage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    datetime = models.DateTimeField(auto_now=True)

login/models.py
from django.db import models

# Create your models here.

profileKu/models.py
from django.db import models

# Create your models here.

landingpage/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(forms.Form):
    status = forms.CharField(max_length=300)

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
def books(request):
    return render(request, 'story8/books.html')

landingpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status

# Create your views here.
def home(request):
    list_status = Status.objects.all().order_by('-datetime')
    return render(request, "story6/landing.html", {'statusq' : list_status})

def add_status(request):
    if request.method == 'POST' :
        form = StatusForm(request.POST)
        if form.is_valid():
            stat = form.data['status']
            stats = Status(status=stat)
            stats.save()
    return redirect('/')

login/views.py
# from django.shortcuts import render, redirect
# from django.contrib.auth import authenticate, login, logout
# from django.http import HttpResponseRedirect, HttpResponse
# from django.urls import reverse
# from django.contrib.auth.models import User


# # Create your views here.
# def homei(request):
#     print("appakek")
#     return render(request, "story9/login.html")

# def login(request):
#     print("a")
#     if request.method == "GET":
#         print("HAHA")
#         return redirect('login:homei')
#         # return render(request, "story7/profile.html")
#     if request.method == "POST":
#         # return render(request, "story7/profile.html")
#         print("APA")
#         if len(request.POST) >= 3:
#             print("post")
#             username_login = request.POST['username']
#             password_login = request.POST['password']
                    
#             user = authenticate(request, username=username_login, password=password_login)

#             if user is not None:
#                 print("hai")
#                 login(request, user)
#                 return redirect('landingpage:home')
#             else:
#                 print("helo")
#                 return redirect('login:homei')
#                 # return render(request, "story7/profile.html")
#         else:
#             print("else")
#             return redirect('login:homei')
#     # return render(request, "story7/profile.html")
#     return render(request, "story9/login.html")

profileKu/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
def profile(request):
    return render(request, 'story7/profile.html')

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
        {% block head %}{% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color:  #D7DBDD; color: #34495E; font-size: 20px;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item navfont">
                <a class="nav-link" href="{% url 'landingpage:home' %}"><b>STATUS</b></a>
                </li>
                <li class="nav-item navfont">
                    <a class="nav-link" href="{% url 'profileKu:profile' %}"><b>PROFILE</b></a>
                </li>
                <li class="nav-item navfont">
                        <a class="nav-link" href="{% url 'books:books' %}"><b>BOOKS</b></a>
                    </li>
                <li class="nav-item navfont">
                        <button class="nav-link change" ><b>UBAH TEMA</b></button>
                </li>
                <li class="nav-item navfont justify-content-end">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}" ><b>LOGOUT</b></a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}" ><b>LOGIN</b></a>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                <p>Halo, {{ user.get_username }}</p>
                {% endif %}
            </div>
        </nav>
        
        {% block body %}{% endblock %}

        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'base.js' %}"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
        {% block script %}{% endblock %}
    </body>
</html>
    

templates/story6/landing.html
{% extends "base.html" %}
{% load static %} 
{% block head %}
        <title>Status</title>
        <link rel="stylesheet" type="text/css" href="{% static 'story7/css/profile.css' %}">
{% endblock %}
{% block body %}
    <body class = "bg-secondary">
        <div class="bg-secondary" id ="home">
                <div class="container">
                        <div id ="sayhello" class="font-weight-bold text-center text-sm-center" style ="color: whitesmoke; font-family: monospace;">
                            <div class= "pt-5"></div>
                            <div class= "pt-5"></div>
                            <h1 class="display-3"><b>Halo, Apa Kabar?</b></h1>
                            <div class= "pb-5"></div>
                            <div class= "pb-5"></div>
                        </div>
                        <div>
                            <form method="POST" action="/add_status/">
                                {% csrf_token %}
                                <div class="form-group">
                                    <textarea name="status" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <button type="submit" name = "submit" class="btn btn-primary btn-lg">Post</button>
                            </form>
                        </div>
                    <div class="row">
                        {% for i in statusq %}
                        {% csrf_token %}
                        <div class="col-md-3">
                            <div class="pt-5 "></div>
                            <div class ="pr-3"></div>
                            <div class="mr-3 ml-3">
                                <div class="card">
                                    <div class="card-body">
                                        <h6>{{ i.status }}</h6>
                                        <p>{{ i.datetime }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="pl-3"></div>
                        <div class = 'pb-5'></div>
                        </div> 
                        {% endfor %}         
                    </div>
                </div>
            </div>
    </body>
    {% endblock %}

templates/story7/profile.html
{% extends "base.html" %}
{% load static %} 
{% block head %}
        <title>Profile</title>
        <link rel="stylesheet" type="text/css" href="{% static 'story7/css/profile.css' %}">
{% endblock %}
{% block body %}
    <body class="bg-danger">
        <div>
            <div class="pt-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-12 text-center">
                            <img src="{% static 'story7/images/foto1.jpg' %}" alt="foto fira"  style ="width :300px; border-radius: 100%;">
                            <h2 class="text-center pt-4 pb-4 name">Shafira Ayu Maharani</h2>
                        </div>
                        <div class="col-md-8 col-sm-12 pink">
                            <div class="accordion-card">
                                <div class="accordion-header">Aktivitas Saat Ini</div>
                                <div class="accordion-content">
                                    Nugas, Makan, Tidur
                                </div>
                                <div class="accordion-header">Pengalaman Organisasi/Kepanitiaan</div>
                                <div class="accordion-content">
                                    <div class="accordion-card">
                                    <div class="accordion-header">FUKI 2019</div>
                                    <div class="accordion-content">
                                        Saya menjadi staf Biro Humas.
                                    </div>
                                    <div class="accordion-header">COMPFEST 11</div>
                                    <div class="accordion-content">
                                        Staf Software Engineering Academy
                                    </div>
                                    <div class="accordion-header">SIWAK-NG 2019</div>
                                    <div class="accordion-content">
                                        Wakil Penanggungjawab Humas dan Publikasi
                                    </div>
                                    <div class="accordion-header">Wisuda Genap</div>
                                    <div class="accordion-content">
                                        Staf LO
                                    </div>
                                    <div class="accordion-header">BETIS 2020</div>
                                    <div class="accordion-content">
                                        Wakil Penanggungjawab Dokumentasi
                                    </div>
                                    <div class="accordion-header">Grand Launching AISCO</div>
                                    <div class="accordion-content">
                                        Penanggungjawab Humas Publikasi Dokumentasi dan Dekorasi
                                    </div>
                                    </div>
                                </div>
                                <div class="accordion-header">Prestasi</div>
                                <div class="accordion-content">
                                    Coming Soon :)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </body>
    {% endblock %}
    {% block script %}
    <script src="{% static 'story7/js/profile.js' %}"></script>
    {% endblock %}

templates/story8/books.html
{% extends "base.html" %}
{% load static %} 
{% block head %}
    <title>Books</title>

{% endblock %}
{% block body %}
    <body class= "bg-light">
        <div class = "container pt-5">
            <div>
                <h1 class= "display-3 text-center pt-5">Mau Cari Buku Apa?</h1>
            </div>
            <div>
                <div class="form-inline justify-content-center pt-3">
                    <div class="form-group-lg mx-sm-3 mb-2">
                        <input type="text" class="form-control" id="pencarian" placeholder="Cari">
                    </div>
                    <button type="submit" class="search btn btn-secondary">Cari</button>
                </div>
            </div>
            <div>
                <table class="table pt-5 text-center">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Judul</th>
                        <th scope="col">Penulis</th>
                        
                        <th scope="col">Terbitan</th>
                        
                        <th scope="col">Sampul</th>
                        </tr>
                    </thead>
                    <tbody class="text-center" id="book">
                        
                    </tbody>
                    </table>
            </div>
        </div>
    </body>
{% endblock %}
{% block script %}
    <script src="{% static 'story8/js/ajax.js' %}"></script>
{% endblock %}